### ISSUE TITLE
Build for other operating systems

### ISSUE THREAD

**Issue by EugSh1** [Pharal1/TheUltimate-Krestiki-Noliki#1]
This game looks very promising! However, unfortunately there are no builds for other operating systems such as macOS and Linux. Please release a build for macOS and Linux. I'm sure the players will be very satisfied!

**Comment by Pharal1** [comment]
I fucking don't know how to build it on linux

with love, pharal1

**Comment by EugSh1** [comment]
Thank you for your comprehensive response!
